---

- name: Install brew cask packages
  community.general.homebrew_cask:
    update_homebrew: true
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
    global: true
  loop: "{{ homebrew_cask_apps }}"
