- name: Install personal GUI apps (casks)
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
    - spotify
    - steam
    - discord
    - signal
    - utm   # macOS virtualization solution
